name: tizo_challange
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  lottie: ^3.1.3
  persistent_bottom_nav_bar: ^6.2.1
  shimmer: ^3.0.0
  comment_sheet: ^0.0.1
  sliding_up_panel: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0  
  hive_generator: ^1.1.0  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_animation.json
    - assets/no_post.png
